{
 "title": "app-monitor-linux-vm",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "process",
    "label": "Process List",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs{instance=~\"$host\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Processes on selected host",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usge",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\"}) by (instance)"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate( node_cpu_seconds_total{mode=\"idle\"}[$__range])"
    }
   ]
  },
  { "title": "Process wise details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Detail panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (groupname)(rate(namedprocess_namegroup_memory_bytes{instance=\"$host\",groupname=~\"$process\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (groupname)(rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$host\",groupname=~\"$process\"}[$__range]))"
    },
    {
     "expr": "sum((time()-(namedprocess_namegroup_oldest_start_time_seconds{instance=\"$host\",groupname=~\"$process\"}>0))) by (groupname)"
    }
   ]
  },
  { "title": "CPU and Memory usage graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top processes by Used  memory",
   "type": "timeseries",
   "description": "Memory Used by Processes, counted as Resident Memory + Space used in Swap Space",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,(\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$process\", memtype=\"swapped\",instance=~\"$host\"}[$__range])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$process\", memtype=\"resident\",instance=~\"$host\"}[$__range]))))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (groupname) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$process\"}[$__range]) *100))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Extras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total memory used per process",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(namedprocess_namegroup_memory_bytes{ instance=\"$host\", memtype=\"swapped\",groupname=~\"$process\"}[$__range])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$host\",memtype=\"resident\",groupname=~\"$process\"}[$__range])"
    }
   ]
  }
 ]
}