{
 "title": "Linux VMs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(nodename)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$host\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Details of all live nodes ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Basic details of linux machines",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (nodename, instance) (node_uname_info)"
    },
    {
     "expr": "sum by (instance)(node_memory_MemTotal_bytes)"
    },
    {
     "expr": "sum by (instance)(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))"
    },
    {
     "expr": "sum by (instance)(node_filesystem_size_bytes)"
    }
   ]
  },
  { "title": "Details of selected host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$ip\"} - node_boot_time_seconds{instance=\"$ip\"}"
    }
   ]
  },
  {
   "title": "CPU Usage(t)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"$ip\",mode=\"idle\"}[$__range])) * 100)"
    }
   ]
  },
  {
   "title": "Egress(t)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$ip\"}[$__range])) by (instance) "
    }
   ]
  },
  {
   "title": "Ingress(t)",
   "type": "stat",
   "description": "The average network traffic received, per second, over the last minute (in bytes)",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$ip\"}[$__range])) by (instance) "
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$ip\"}"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$ip\"} - node_memory_MemAvailable_bytes{instance=\"$ip\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( node_memory_MemAvailable_bytes{instance=\"$ip\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage(t)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"$ip\"}[$__range]) - (avg_over_time(node_memory_Cached_bytes{instance=\"$ip\"}[$__range]) + avg_over_time(node_memory_Buffers_bytes{instance=\"$ip\"}[$__range]) + avg_over_time(node_memory_MemFree_bytes{instance=\"$ip\"}[$__range]))) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$ip\"}[$__range])) * 100"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$ip\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$ip\",mountpoint=\"/\"}-node_filesystem_avail_bytes{instance=\"$ip\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$ip\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) "
    }
   ]
  }
 ]
}