{
 "title": "Linux-vm-alert",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Basic Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Basic details",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance,nodename) (node_uname_info)"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Machine Down Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up == 0" }
   ]
  },
  {
   "title": "Memory Usage Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[$__range]) + avg_over_time(node_memory_Cached_bytes[$__range]) + avg_over_time(node_memory_Buffers_bytes[$__range])) / avg_over_time(node_memory_MemTotal_bytes[$__range])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux VM CPU usage alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__range])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100)/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}