{
 "title": "Node Stats and Alerts - subit",
 "description": "This dashboard shows cpu, memory and disk stats for linux and container nodes. Default alerts are configured for linux nodes.",
 "tags": [
  "alerts",
  "linux",
  "docker",
  "container",
  "cpu",
  "ram",
  "disk"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Cron Job Exit Code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " (node_cron_job_exit_code)", "legendFormat": "{{instance}} - {{code}}" }
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{mountpoint=\"/hostfs\"} / 1024 / 1024 ) / (node_filesystem_size_bytes{mountpoint=\"/hostfs\"}  / 1024 / 1024))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Running exporters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}