{
 "title": "pod details",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod List",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Pods running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_created)" }
   ]
  },
  {
   "title": "Top 5 CPU consuming pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}[$__range]))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Memory usage graph",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$pod\",image!=\"\"} - container_memory_cache{namespace=\"$namespace\",pod=~\"$pod\",image!=\"\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(container_memory_usage_bytes{pod=~\"$pod\",namespace=~\"$namespace\",image!=\"\"} - container_memory_cache{pod=~\"$pod\",namespace=~\"$namespace\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Pod cpu usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__range])*100)"
    }
   ]
  },
  {
   "title": "Memory limits/requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\",namespace=~\"$namespace\"}\n) by (pod,namespace)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$pod\",namespace=~\"$namespace\"}\n) by (pod,namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}