{
 "title": "svc-status-alert",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "IIS Site status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "count (windows_iis_current_connections) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Application pool status(Windows IIS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{state=\"Running\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "TahoeUtilities service status (Linux)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_cpu_seconds_total{groupname=\"TahoeUtilities_\"}) by (mode)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Cormatix service status (Windows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "count(windows_process_start_time{process=\"CormatixServiceHelper\"}) by (process_id)",
     "legendFormat": "CormatixServiceHelper"
    }
   ]
  },
  {
   "title": "Influx service status (Windows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count(windows_process_start_time{process=\"influxd\"})",
     "legendFormat": "influxd"
    }
   ]
  },
  {
   "title": "Redis-server status (Windows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "count(windows_process_start_time{process=\"redis-server\"})",
     "legendFormat": "redis-server"
    }
   ]
  }
 ]
}