{
 "title": "Win Svc Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pre_FTP_Singlefileperday_ [ 1,2,3 ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_singlefileperday_1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_singlefileperday_1\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_singlefileperday_2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_singlefileperday_2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_singlefileperday_3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_singlefileperday_3\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pre_Ftp_ ( others --- VM 2 )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "pre_ftp_radiance_1_min2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"pre_ftp_radiance_1_min2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_cleanmax-solar",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_cleanmax-solar\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_continuum",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_continuum\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_demo-solar",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_demo-solar\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_demo-wind",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_demo-wind\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_inox",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_inox\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_integrumsolar",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_integrumsolar\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_sunsolarwind",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_sunsolarwind\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_stride",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_stride\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_sma",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_sma\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_ipcl",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_ipcl\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_konery",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_konery\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_koneryn",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_koneryn\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_kovai",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_kovai\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_FTP_Refex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_refex",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex3\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex4",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex4\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex5\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex6",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex6\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex7",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex7\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex8",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex8\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex9",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex9\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex10",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex10\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex11",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex11\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_refex12",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_refex12\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_FTP_Radiane_MT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_radiane_mt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiane_mt\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_FTP_Radiance [ _SMA, _SMATest, _test, _Test2 ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_radiance_sma",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_sma\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_smatest",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_smatest\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_test",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_test\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_test2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_test2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_Ftp_ [ _AIG-Core, _Apollo, _Cormatix_2, _EOSE, _Gensol, _Gensol1, _Indolfin, _integrum ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_aig-core",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_aig-core\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_apollo",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_apollo\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_cormatix_2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_cormatix_2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_eose",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_eose\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_gensol",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_gensol\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_gensol1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_gensol1\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_indolfin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_indolfin\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_integrum",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_integrum\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp-CormatixFileServer [_Nexus, _Uneecops_New]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-cormatixfileserver_nexus",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-cormatixfileserver_nexus\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-cormatixfileserver_uneecops_new",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-cormatixfileserver_uneecops_new\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp-E-FTP_Radiane_MT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-e-ftp_radiane_mt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-e-ftp_radiane_mt\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_Radiance_1_Min [9,10,11,12]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp_radiance_1min_9",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp_radiance_1min_9\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp_radiance_1min10",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp_radiance_1min10\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp_radiance_1_min11",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp_radiance_1_min11\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp_radiance_1_min12",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp_radiance_1_min12\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_Radiance_SingleFilePerDay_34",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp_radiance_singlefileperday_34",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp_radiance_singlefileperday_34\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp_FTP_Radiance & _Min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_radiance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_mintest",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_mintest\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min1\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min3\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min4",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min4\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min5\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_1_min6",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_1_min6\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp-F-FTP_Radiance_SingleFilePerDay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-f-ftp_radiance_singlefileperday_2",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-f-ftp_radiance_singlefileperday_2\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-f-ftp_radiance_singlefileperday_3",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-f-ftp_radiance_singlefileperday_3\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-f-ftp_radiance_singlefileperday_4",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-f-ftp_radiance_singlefileperday_4\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreFtp-ftp_Radiance_SingleFilePerDay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "preftp-ftp_radiance_singlefileperday_1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_1\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_test",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_test\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_5\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_6",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_6\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_7",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_7\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_8",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_8\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_9",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_9\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_10",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_10\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_11",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_11\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_12",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_12\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_13",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_13\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_14",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_14\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_15",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_15\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_16",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_16\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_17",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_17\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_18",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_18\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_19",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_19\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_20",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_20\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_21",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_21\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_22",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_22\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_23",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_23\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_24",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_24\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_25",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_25\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_26",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_26\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_27",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_27\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_28",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_28\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_29",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_29\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_30",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_30\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_31",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_31\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_32",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_32\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    },
    {
     "title": "preftp-ftp_radiance_singlefileperday_33",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "windows_service_state{name=\"preftp-ftp_radiance_singlefileperday_33\",state=\"stopped\"}",
       "legendFormat": "{{name}} - {{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}