{
 "title": "Windows Applications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Hostname", "query": { "query": "label_values(hostname)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(windows_cs_hostname{hostname=~\"$host\"},instance)"
    }
   },
   {
    "name": "process",
    "label": "Process List",
    "query": {
     "query": "label_values(windows_process_cpu_time_total{instance=\"$ip\"},process)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Process on selected host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (process) (windows_process_cpu_time_total{instance=\"$ip\"}))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windows_memory_available_bytes" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(windows_cs_physical_memory_bytes{instance=~\"$ip\"}[$__range]) - avg_over_time(windows_os_physical_memory_free_bytes{instance=~\"$ip\"}[$__range])"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[$__range])) * 100)"
    }
   ]
  },
  {
   "title": "Process with process ids",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (process,process_id) (windows_process_handles{instance=~\"$ip\",process=~\"$process\"})"
    },
    {
     "expr": "sum by (process,process_id)(time() - windows_process_start_time{instance=~\"$ip\",process=~\"$process\"})"
    },
    {
     "expr": "avg by (process,process_id)(rate(windows_process_cpu_time_total{instance=~\"$ip\",process=~\"$process\"}[$__range]) * 100)"
    },
    {
     "expr": "sum by (process,process_id)(windows_process_working_set_private_bytes{instance=~\"$ip\",process=~\"$process\"} offset $__range)"
    }
   ]
  },
  {
   "title": "cpu min and max usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (process,process_id) (rate(windows_process_cpu_time_total{process=~\"$process\",process!=\"Idle\"}[$__range])) * 100",
     "legendFormat": "{{process}} {{process_id}}"
    }
   ]
  },
  {
   "title": "Memory min and max usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (process,process_id)(windows_process_working_set_private_bytes{instance=~\"$ip\",process=~\"$process\"} offset $__range)",
     "legendFormat": "{{process}} {{process_id}}"
    }
   ]
  }
 ]
}