{
 "title": "windows-vm-alert",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "win_svc Cornotifer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "windows_service_state{name=\"cornotifer\",state=\"stopped\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "win_svc Cormatix",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "windows_service_state{name=\"cormatix\",state=\"stopped\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Basic Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Basic details",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (hostname,instance) (windows_cs_hostname)"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Machine Down Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    { "expr": "up == 0" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(100 - 100 * avg_over_time(windows_os_physical_memory_free_bytes[$__range]) / avg_over_time(windows_cs_physical_memory_bytes[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes"
    }
   ]
  },
  {
   "title": "Windows machines cpu usage alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[$__range])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}