- name: Adding prometheus helm repo
  kubernetes.core.helm_repository:
    repo_name: "{{ prometheus.chartRepoName }}"
    repo_url: "{{ grafana.chartRepoUrl}}"

- name: "Deploy prometheus chart {{ prometheus.chartVersion }}  with values loaded from template"
  kubernetes.core.helm:
    name: "{{ prometheus.releaseName }}"
    release_namespace: "{{ namespaceName }}"
    create_namespace: true
    update_repo_cache: True
    chart_ref: "{{ prometheus.chartName }}"
    chart_version: "{{ prometheus.chartVersion }}"
    values: "{{ lookup('template', 'prometheus-values.yaml') | from_yaml }}"