- name: Adding open-telemetry helm repo
  kubernetes.core.helm_repository:
    repo_name: "{{ otelOperator.chartRepoName }}"
    repo_url: "{{ otelOperator.chartRepoUrl }}"

- name: "Deploy opentelemetry-operator helm chart {{ otelOperator.chartVersion }}  with values loaded from template"
  kubernetes.core.helm:
    name: "{{ otelOperator.releaseName }}"
    release_namespace: "{{ namespaceName }}"
    create_namespace: true
    update_repo_cache: True
    chart_ref: "{{ otelOperator.chartName }}"
    chart_version: "{{ otelOperator.chartVersion }}"
#    values: "{{ lookup('template', 'otel-collector-opt-values.yaml') | from_yaml }}"
    values_files:
      - "{{ role_path }}/files/otel-collector-opt-values.yaml"    