- name: Adding grafana helm repo
  kubernetes.core.helm_repository:
    repo_name: "{{ grafana.repoName }}"
    repo_url: "{{ grafana.repoUrl}}"

- name: "Deploy Grafana chart {{ grafana.chartVersion }}  with values loaded from template"
  kubernetes.core.helm:
    name: "{{ grafana.releaseName }}"
    release_namespace: "{{ namespaceName }}"
    create_namespace: true
    update_repo_cache: True
    chart_ref: "{{ grafana.chartName }}"
    chart_version: "{{ grafana.chartVersion }}"
    values: "{{ lookup('template', 'grafana-values.yaml') | from_yaml }}"