- name: Adding grafana helm repo
  kubernetes.core.helm_repository:
    repo_name: "{{ grafana.chartRepoName }}"
    repo_url: "{{ grafana.chartRepoUrl}}"

- name: "Deploy loki chart {{ loki.chartVersion }}  with values loaded from template"
  kubernetes.core.helm:
    name: "{{ loki.releaseName }}"
    release_namespace: "{{ namespaceName }}"
    create_namespace: true
    update_repo_cache: True
    chart_ref: "{{ loki.chartName }}"
    chart_version: "{{ loki.chartVersion }}"
    values_files:
      - "{{ role_path }}/files/loki-values.yaml" 



# #   values: "{{ lookup('template', 'loki-values.yaml') | from_yaml }}"